#!/usr/bin/perl
# Compare two Nemerle-generated IL files, generated by Portable.NET's ildasm

sub work
{
  my $in = shift;
  my $out = shift;
  open(IN,"<$in") or die("cannot open $in");
  open(OUT,">$out");

  while (<IN>) {
	s/\?L[0-9a-f]+/L/g;
	s/(_N\S*?)[0-9]+([\s:\)])/$1$2/g;
	s/header: [0-9a-f]+//g;
	s/stage[123]/stage0/g;
	print OUT $_;
  }
}

my $tmp = "$ENV{HOME}/tmp";

work($ARGV[0], "$tmp/il-diff.1");
work($ARGV[1], "$tmp/il-diff.2");
system("diff -u $tmp/il-diff.1 $tmp/il-diff.2");
