#!/bin/bash
rm -f _dynamic-library_.dll_library-consumer_.exe
./ncc.exe ../lib/core.n ../lib/list.n ../lib/option.n testsuite/misc/dynamic-library.n
mv -f out.cs _dynamic-library_.cs
csc /target:library /debug+ /nowarn:162 /out:_dynamic-library_.dll _dynamic-library_.cs
./ncc.exe /reference:_dynamic-library_.dll testsuite/misc/library-consumer.n
mv -f out.cs _library-consumer_.cs
csc /debug+ /nowarn:162 /out:_library-consumer_.exe /reference:_dynamic-library_.dll _library-consumer_.cs
./_library-consumer_.exe
