//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nemerle.VisualStudio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nemerle.VisualStudio.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemerle.
        /// </summary>
        internal static string _100 {
            get {
                return ResourceManager.GetString("100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDQ8HJPRZZE3QJKCEAEZZEZDJ0CJPKMPEJEIZQEZQARPARHDHAC0D3CQDCEJPIJCE3P2K9E9IDJCMEMHRKQDHAQ1QMZRAPHAEQP2HQP3IAQMZDKIJRI3CZQJIIDTECII.
        /// </summary>
        internal static string _104 {
            get {
                return ResourceManager.GetString("104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K8RHAQK0A9DZMQM8AQI0PPM9HZD9E9RPA9Q1PCJ9JDJ2IQA0Q8AQHMARIEAHRJC0E2R2JJQRDKAPMEM9RIDKPCDJMJZQDHD0IAD1I3E9QAP9EEDKCQQCEAE3DAKAPTEQ.
        /// </summary>
        internal static string _10408 {
            get {
                return ResourceManager.GetString("10408", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KHJ1HZR1P2EMZKCRZCMAMCZEMPKEPEZJP1CEKQCEHDICAKMARHCTK9KJM8IMARZ3QEZCJ2RQIKEMHZR0MAE1JEQKZAIPCMP2PAE2EZZIMCJ8K9ZJAHI0EKD9MDAPE2HC.
        /// </summary>
        internal static string _1042 {
            get {
                return ResourceManager.GetString("1042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZRRZZCP8HEA1C8J2QTP3IEC0P3EEHQHRQACRZDJ3EHP2RQDZI2ZKMJAEATQ3HRP0MRZHIDD2DPPRE0RQARA8C2C3C0QTQKZPR1PAHPZJI2ADACHCIEKIICHJA3QDIRA1.
        /// </summary>
        internal static string _105 {
            get {
                return ResourceManager.GetString("105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKAKZJD8C0EHEIKPQ9MRD3A1M1QJPJCJKDRZMMRCJKPIM3Z1H3EZIHRMJIHCKMPERZAKEJP0RMPDEDZCCJAMK8ITPTEZCRDZHKQ0QZRQCIZDD3D9AEQJMIM0AHKAKZJD8C0EHEIKPQ9MRD3A1M1QJPJCJKDRZMMRCJKPIM3Z1H3EZIHRMJIHCKMPERZAKEJP0RMPDEDZCCJAMK8ITPTEZCRDZHKQ0QZRQCIZDD3D9AEQJMIM0AHC0JDP9.
        /// </summary>
        internal static string _10508 {
            get {
                return ResourceManager.GetString("10508", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Form.
        /// </summary>
        internal static string _2237 {
            get {
                return ResourceManager.GetString("2237", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string _2245 {
            get {
                return ResourceManager.GetString("2245", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro.
        /// </summary>
        internal static string _2246 {
            get {
                return ResourceManager.GetString("2246", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro attribute (assembly level).
        /// </summary>
        internal static string _2247 {
            get {
                return ResourceManager.GetString("2247", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An empty class definiton.
        /// </summary>
        internal static string _2262 {
            get {
                return ResourceManager.GetString("2262", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An empty macro definiton.
        /// </summary>
        internal static string _2263 {
            get {
                return ResourceManager.GetString("2263", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A blank Windows Form.
        /// </summary>
        internal static string _2264 {
            get {
                return ResourceManager.GetString("2264", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An empty macro attribute definiton.
        /// </summary>
        internal static string _2265 {
            get {
                return ResourceManager.GetString("2265", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Control.
        /// </summary>
        internal static string _2295 {
            get {
                return ResourceManager.GetString("2295", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A reusable Windows Forms control.
        /// </summary>
        internal static string _2296 {
            get {
                return ResourceManager.GetString("2296", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text File.
        /// </summary>
        internal static string _2316 {
            get {
                return ResourceManager.GetString("2316", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An empty text file.
        /// </summary>
        internal static string _2317 {
            get {
                return ResourceManager.GetString("2317", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources File.
        /// </summary>
        internal static string _2390 {
            get {
                return ResourceManager.GetString("2390", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file for storing resources.
        /// </summary>
        internal static string _2391 {
            get {
                return ResourceManager.GetString("2391", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon _300 {
            get {
                object obj = ResourceManager.GetObject("300", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _301 {
            get {
                object obj = ResourceManager.GetObject("301", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string ApplicationCaption {
            get {
                return ResourceManager.GetString("ApplicationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Icon.
        /// </summary>
        internal static string ApplicationIcon {
            get {
                return ResourceManager.GetString("ApplicationIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the .ico file to use as your application icon..
        /// </summary>
        internal static string ApplicationIconDescription {
            get {
                return ResourceManager.GetString("ApplicationIconDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Name.
        /// </summary>
        internal static string AssemblyName {
            get {
                return ResourceManager.GetString("AssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the output file that will hold assembly metadata..
        /// </summary>
        internal static string AssemblyNameDescription {
            get {
                return ResourceManager.GetString("AssemblyNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Types.
        /// </summary>
        internal static string BaseTypesNodeText {
            get {
                return ResourceManager.GetString("BaseTypesNodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        internal static string BuildCaption {
            get {
                return ResourceManager.GetString("BuildCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a tool window..
        /// </summary>
        internal static string CannotCreateWindow {
            get {
                return ResourceManager.GetString("CannotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Arguments.
        /// </summary>
        internal static string CmdArgs {
            get {
                return ResourceManager.GetString("CmdArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional arguments passed to starting program..
        /// </summary>
        internal static string CmdArgsDescription {
            get {
                return ResourceManager.GetString("CmdArgsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string DebugCaption {
            get {
                return ResourceManager.GetString("DebugCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug symbols.
        /// </summary>
        internal static string DebugSymbols {
            get {
                return ResourceManager.GetString("DebugSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines whether to create *.pdb file containing debug symbols.
        /// </summary>
        internal static string DebugSymbolsDescription {
            get {
                return ResourceManager.GetString("DebugSymbolsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML documentation file.
        /// </summary>
        internal static string DecumentationFile {
            get {
                return ResourceManager.GetString("DecumentationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the name of a file into which documentation comments will be processed..
        /// </summary>
        internal static string DecumentationFileDescription {
            get {
                return ResourceManager.GetString("DecumentationFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Namespace.
        /// </summary>
        internal static string DefaultNamespace {
            get {
                return ResourceManager.GetString("DefaultNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Namespace.
        /// </summary>
        internal static string DefaultNamespace1 {
            get {
                return ResourceManager.GetString("DefaultNamespace1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the default namespace for added items, such as classes, that are added via the Add New Item Dialog Box..
        /// </summary>
        internal static string DefaultNamespaceDescription {
            get {
                return ResourceManager.GetString("DefaultNamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditional compilation symbols.
        /// </summary>
        internal static string DefineConstants {
            get {
                return ResourceManager.GetString("DefineConstants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies symbols on which to perform conditional compilation. Separate symbols with a semicolon..
        /// </summary>
        internal static string DefineConstantsDescription {
            get {
                return ResourceManager.GetString("DefineConstantsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        internal static string ErrorPrefix {
            get {
                return ResourceManager.GetString("ErrorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string GeneralCaption {
            get {
                return ResourceManager.GetString("GeneralCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Snippet.
        /// </summary>
        internal static string InsertSnippet {
            get {
                return ResourceManager.GetString("InsertSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemerle.
        /// </summary>
        internal static string Nemerle {
            get {
                return ResourceManager.GetString("Nemerle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemerle File (*.n)
        ///*.n.
        /// </summary>
        internal static string NemerleFormatFilter {
            get {
                return ResourceManager.GetString("NemerleFormatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyNested Project File (*.nestedproj){0}*.nestedproj{1}.
        /// </summary>
        internal static string NestedProjectFileAssemblyFilter {
            get {
                return ResourceManager.GetString("NestedProjectFileAssemblyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output File.
        /// </summary>
        internal static string OutputFile {
            get {
                return ResourceManager.GetString("OutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the project&apos;s primary output file..
        /// </summary>
        internal static string OutputFileDescription {
            get {
                return ResourceManager.GetString("OutputFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the primary output.
        /// </summary>
        internal static string OutputPathDescription {
            get {
                return ResourceManager.GetString("OutputPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Path (final value).
        /// </summary>
        internal static string OutputPathFinalValue {
            get {
                return ResourceManager.GetString("OutputPathFinalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Type.
        /// </summary>
        internal static string OutputType {
            get {
                return ResourceManager.GetString("OutputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of application to build..
        /// </summary>
        internal static string OutputTypeDescription {
            get {
                return ResourceManager.GetString("OutputTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project File.
        /// </summary>
        internal static string ProjectFile {
            get {
                return ResourceManager.GetString("ProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the file containing build, configuration, and other information about the project..
        /// </summary>
        internal static string ProjectFileDescription {
            get {
                return ResourceManager.GetString("ProjectFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemerle Project File (*.nproj){0}*.nproj{1}.
        /// </summary>
        internal static string ProjectFileExtensionFilter {
            get {
                return ResourceManager.GetString("ProjectFileExtensionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Folder.
        /// </summary>
        internal static string ProjectFolder {
            get {
                return ResourceManager.GetString("ProjectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The absolute location of the project..
        /// </summary>
        internal static string ProjectFolderDescription {
            get {
                return ResourceManager.GetString("ProjectFolderDescription", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap SO_ClearFiltersButton {
            get {
                object obj = ResourceManager.GetObject("SO_ClearFiltersButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SO_Images_24bit {
            get {
                object obj = ResourceManager.GetObject("SO_Images_24bit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SO_Images_32bit {
            get {
                object obj = ResourceManager.GetObject("SO_Images_32bit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SO_TreeViewIcons {
            get {
                object obj = ResourceManager.GetObject("SO_TreeViewIcons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Outliner.
        /// </summary>
        internal static string SourceOutlinerWindowTitle {
            get {
                return ResourceManager.GetString("SourceOutlinerWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Program.
        /// </summary>
        internal static string StartProgram {
            get {
                return ResourceManager.GetString("StartProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location of the starting program..
        /// </summary>
        internal static string StartProgramDescription {
            get {
                return ResourceManager.GetString("StartProgramDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Object.
        /// </summary>
        internal static string StartupObject {
            get {
                return ResourceManager.GetString("StartupObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the class that contains the static Main method that you want called when you launch your application..
        /// </summary>
        internal static string StartupObjectDescription {
            get {
                return ResourceManager.GetString("StartupObjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string StatusPrefix {
            get {
                return ResourceManager.GetString("StatusPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surround With....
        /// </summary>
        internal static string SurroundWith {
            get {
                return ResourceManager.GetString("SurroundWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Platform.
        /// </summary>
        internal static string TargetPlatform {
            get {
                return ResourceManager.GetString("TargetPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of the Common Language Runtime to use for output assembly.
        /// </summary>
        internal static string TargetPlatformDescription {
            get {
                return ResourceManager.GetString("TargetPlatformDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Platform Location.
        /// </summary>
        internal static string TargetPlatformLocation {
            get {
                return ResourceManager.GetString("TargetPlatformLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location of the target platform.
        /// </summary>
        internal static string TargetPlatformLocationDescription {
            get {
                return ResourceManager.GetString("TargetPlatformLocationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Directory.
        /// </summary>
        internal static string WorkingDirectory {
            get {
                return ResourceManager.GetString("WorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial folder..
        /// </summary>
        internal static string WorkingDirectoryDescription {
            get {
                return ResourceManager.GetString("WorkingDirectoryDescription", resourceCulture);
            }
        }
    }
}
