#!/bin/sh

rm -f a.out
time mono ../ncc.exe ../../lib/{aliases,core,list}.n "$@" || exit 1
#time mono ../../boot/ncc.exe ../../lib/{aliases,core,list}.n "$@" || exit 1
mcs -nowarn:162 -o a.out out.cs 2>&1 | grep -v 'Compilation suc'
mono ./a.out
#rm -f a.out out.cs
