#!/bin/sh

rm -f out.exe
export MONO_PATH=../out.stage1/
time mono ../out.stage1/ncc.exe -ignore-confusion ../../lib/aliases.n -r Nemerle.dll "$@" || exit 1
#time mono ../../boot/ncc.exe ../../lib/{aliases,core,list}.n "$@" || exit 1
#mcs -nowarn:162 -o a.out out.cs 2>&1 | grep -v 'Compilation suc'
mono ./out.exe
#rm -f a.out out.cs
