#!/bin/sh
ENGINE=`grep NET_ENGINE ../../config.mak | awk '{print $3}'`
NETFLAGS=`grep NET_FLAGS ../../config.mak | awk '{print $3}'`

rm -f out.exe
export MONO_PATH=../out.stage2/
time $ENGINE $NETFLAGS ../out.stage2/ncc.exe -ignore-confusion -bar+ -no-stdlib -r ../out.stage2/Nemerle.stage2 -r:System "$@" || exit 1
time $ENGINE $NETFLAGS ./out.exe || echo "Non zero exit code."

