#!/usr/bin/perl

open(F,"<$ARGV[0]");
while (<F>) {
if (/^\s+\d+\s+(\d+)\s+\d+\s+\d+\s+\d+\s+(.*)$/) {
  $r{$2} = $1;
}
}

open(F,"<$ARGV[1]");
while (<F>) {
if (/^\s+\d+\s+(\d+)\s+\d+\s+\d+\s+\d+\s+(.*)$/) {
$old = $r{$2};
$new = $1;
if ($old == 0) { $ratio = "N/A"; }
else { $ratio = sprintf "%.2f", $new/$old; 
if ($new/$old > 5) { $ratio .= " XXX" }
}
printf "%20s %s", "[$old, $ratio]", $_;
} else { print }
}

