#!/bin/sh
sort -k2 -n nc-prof-log | grep Load | tail -1 | awk '{print ($2/1000"% "$4)}'
sort -k2 -n nc-prof-log | grep GetToken | tail -1 | awk '{print ($2/1000"% "$4)}'
LEX=`sort -k2 -n nc-prof-log | grep GetToken | tail -1 | awk '{print $2}'`
sort -k2 -n nc-prof-log | grep PreParser:ParseTop | tail -1 | awk '{print (($2-'$LEX')/1000"% "$4)}'
sort -k2 -n nc-prof-log | grep MainParser:ParseTop | tail -1 | awk '{print ($2/1000"% "$4)}'
sort -k2 -n nc-prof-log | grep TypeBuilder:Run | tail -1 | awk '{print ($2/1000"% "$4)}'
sort -k2 -n nc-prof-log | grep add_declarations | tail -1 | awk '{print ($2/1000"% "$4)}'
sort -k2 -n nc-prof-log | grep TypeMethod | tail -1 | awk '{print ($2/1000"% "$4)}'
sort -k2 -n nc-prof-log | grep cg_global_fun | tail -1 | awk '{print ($2/1000"% "$4)}'
sort -k2 -n nc-prof-log | grep EmitMethod | tail -1 | awk '{print ($2/1000"% "$4)}'
