#!/bin/sh

export LD_LIBRARY_PATH=$HOME/nemerle/misc/profiler
mono --profile=x  \
	../boot/ncc.exe -q -no-stdlib -r:mscorlib -r:System -pedantic-lexer -target-library -out:out.stage1/Nemerle.Compiler.stage1.dll \
        -reference:out.stage1/Nemerle.stage1.dll \
         integertype.n cgexpr.n cgopt.n external.n xmldump.n cgil.n cgmatch.n globalenv.n localvalue.n macros.n macroregistry.n members.n util.n scan_globals.n flags.n lexer.n cgtree.n passes.n tycon.n typingcontext.n typattern.n tyexpr.n tyinfo.n ast.n parsetree.n typedtree.n parser.n tycodec.n tyvars.n tyutil.n itypemodifier.n attribute.n constantfolder.n > prof-log

exit 0

mono --profile=x\
	../boot/ncc.exe -q -no-stdlib -r:mscorlib -r:System -pedantic-lexer -target-library -out:out.stage1/Nemerle.stage1.dll  ../lib/core.n ../lib/getopt.n ../lib/hashtable.n ../lib/icollection.n ../lib/ienumerable.n ../lib/ienumerator.n ../lib/input.n ../lib/linkedlist.n ../lib/list.n ../lib/option.n ../lib/queue.n ../lib/stack.n ../lib/tree.n ../lib/idictionaryenumerator.n ../lib/idictionary.n ../lib/dictionaryentry.n ../lib/heap.n ../lib/icomparable.n ../lib/narray.n ../lib/nstring.n > prof-log

exit 0

# sort -k1 -n prof-log | less
# sort -k2 -n prof-log | less
# sort -k3 -n prof-log | less
