#!/usr/bin/perl -i

use File::stat;

$root = "src/nem-examples";

while (<>) {
  if (/^\[\[code src=([^\s]*) part=([^\s]*) \]\]/) {
    $fn = $1;
    $def = $2;
    $can_cache = 0;
    if (-f "$root/$fn--$def") {
      $sb1 = stat ("$root/$fn--$def");
      $sb2 = stat ("$root/$fn");
      $can_cache = 1 
        if ($sb1->ctime > $sb2->ctime);
    }

    if ($can_cache) {
      #print STDERR ".";
      open (IN, "< $root/$fn--$def");
    } else {
      #print STDERR "*";
      open (IN, "../misc/htmldumper/dumphtml src/nem-examples/$fn $def |");
      open (OUT, "> $root/$fn--$def");
    }
    while (<IN>) {
      print;
      print OUT $_ unless ($can_cache);
    }
  } else {
    print;
  }
}
#print STDERR "\n";
