#!/bin/sh

ls ../../ncc/testsuite/frommcs/ | grep "\.n" | sed 's/\.n//' | sort | \
grep -vE "(test-346|test-65|test-262)" > listprev

## filter out tests, which we fixed by hand and added to frommcs
# test-346 - semantic diff, we do not exclude override methods in overloading
# test-65 - comparing struct declared as object to null - conversion remove that info FIXME?
# test-262 - http://nemerle.org/bugs/view.php?id=389 FIXME


grep PASS log | sed 's/PASS://' | sed 's/ .*tests\///' | sed 's/:.*//' | sort > listnow
diff -u listprev listnow
