#!/bin/sh

ls ../../ncc/testsuite/frommcs/ | grep "\.n" | sed 's/\.n//' | sort | \
grep -vE "(test-346|test-65|test-313|test-166|verify-7|test-115)" > listprev

## filter out tests, which we fixed by hand and added to frommcs
# test-346 - semantic diff, we do not exclude override methods in overloading
# test-65 - comparing struct declared as object to null - conversion remove that info FIXME?
# test-313 - we manually specify explicit implemented method name, so it can't be QID
# test-166 - after conversion we loose information that variable was upcasted to interface
# verify-7 - original C# example loops infinitely
# test-115 - double operator conversion... 

grep PASS log | sed 's/PASS://' | sed 's/ .*tests\///' | sed 's/:.*//' | sort > listnow
diff -u listprev listnow
