#!/bin/sh
DIR=`dirname $0`
ENGINE=`grep "^NET_ENGINE" ./$DIR/../../config.mak | awk '{print $3}'`

for i in tests/*.cs; do 
  echo "-----------$i-----------------"
  $ENGINE ./cs2n.exe $i `echo $i | sed 's/cs/n/g'`; 
done;
