#!/bin/sh
DIR=`dirname $0`
ENGINE=`grep "^NET_ENGINE" ./$DIR/../../config.mak | awk '{print $3}'`

directory=

if [ "$#" -gt "0" ]; then 
  directory=$1
fi

for i in $directory/*.cs; do 
  echo "-----------$i-----------------";
  $ENGINE ./cs2n.exe $i `echo $i | sed 's/cs/n/g'`; 
done;
