#!/bin/sh

directory=
if [ "$#" -gt "0" ]; then 
  directory=$1
else
  directory=tests
fi

rm -fr $directory/*.exe $directory/*.dll $directory/*.log $directory/*.n
for i in `grep unsafe $directory/*.cs | sed 's/:.*//'`; do rm -f $i; done;
for i in `grep yield $directory/*.cs | sed 's/:.*//'`; do rm -f $i; done;
for i in `grep "__arglist" $directory/*.cs | sed 's/:.*//'`; do rm -f $i; done;
perl -i -pe 's/\-langversion:default//g' `find ./$directory/ | grep "\.cs$" | xargs`
perl -i -pe 's/\-optimize+//g' `find ./$directory/ | grep "\.cs$" | xargs`
perl -i -pe 's/\-warn:4//g' `find ./$directory/ | grep "\.cs$" | xargs`
perl -i -pe 's/\-warnaserror//g' `find ./$directory/ | grep "\.cs$" | xargs`
perl -i -pe 's/\-nowarn:\d+//g' `find ./$directory/ | grep "\.cs$" | xargs`
#fixme: this test takes exponential time to convert (1+(2+(3+....)))
#rm -f $directory/test-233.cs
#fixme: return inside while (true) { try { .. } } not converted properly
rm -f $directory/test-257.cs

#fixme: ncc shoudl not comple it
rm -f $directory/cs0156.cs

rm -f $directory/cs0157-2.cs

#after conversion this error disappears
rm -f $directory/cs0156-2.cs
rm -f $directory/cs0157-3.cs
