#!/bin/sh

rm -fr ./tests/*.exe ./tests/*.dll ./tests/*.log ./tests/*.n
for i in `grep unsafe tests/*.cs | sed 's/:.*//'`; do rm -f $i; done;
for i in `grep "__arglist" tests/*.cs | sed 's/:.*//'`; do rm -f $i; done;
perl -i -pe 's/\-langversion:default//g' `find ./tests/ | grep "\.cs$" | xargs`
perl -i -pe 's/\-optimize+//g' `find ./tests/ | grep "\.cs$" | xargs`
perl -i -pe 's/\-warn:4//g' `find ./tests/ | grep "\.cs$" | xargs`
perl -i -pe 's/\-warnaserror//g' `find ./tests/ | grep "\.cs$" | xargs`
perl -i -pe 's/\-nowarn:\d+//g' `find ./tests/ | grep "\.cs$" | xargs`
#fixme: this test takes exponential time to convert (1+(2+(3+....)))
#rm -f tests/test-233.cs
#fixme: return inside while (true) { try { .. } } not converted properly
rm -f tests/test-257.cs
