#!/bin/sh

directory=
if [ "$#" -gt "0" ]; then 
  directory=$1
else
  directory=tests
fi

rm -fr $directory/*.exe $directory/*.dll $directory/*.log $directory/*.n
for i in `grep unsafe $directory/*.cs | sed 's/:.*//'`; do rm -f $i; done;
#for i in `grep yield $directory/*.cs | sed 's/:.*//'`; do rm -f $i; done;
for i in `grep "__arglist" $directory/*.cs | sed 's/:.*//'`; do rm -f $i; done;
perl -i -pe 's/\-langversion:default//g' `find ./$directory/ | grep "\.cs$" | xargs`
perl -i -pe 's/\-optimize\+//g' `find ./$directory/ | grep "\.cs$" | xargs`
perl -i -pe 's/(\-|\/)warnaserror//g' `find ./$directory/ | grep "\.cs$" | xargs`

###### tests/*.cs

# the C# example contains infinite loop
rm -f $directory/verify-7.cs

#fixme: this test takes exponential time to convert (1+(2+(3+....)))
# this test is rejected anyway by 'unsafe', but the problem remains
#rm -f $directory/test-233.cs

###### errors/*.cs

#fixme: ncc should not comple it
rm -f $directory/cs0156.cs

rm -f $directory/cs0157-2.cs

#after conversion this error disappears
rm -f $directory/cs0156-2.cs
rm -f $directory/cs0157-3.cs
