#!/bin/sh

export CSCOMPILE='mono ../../ncc/out.stage3/ncc.exe';
export TEST_RUNTIME=mono

for i in tests/*.n; do
  name=`echo $i | sed 's/\.n//g'`;
  options=`sed -n 's,^// Compiler options:,,p' $i`; \
  case $options in *-t:library*) ext=dll ;; *-t:module*) ext=netmodule ;; *) ext=exe ;; esac; \
  testlogfile="$name.log" ; \
  echo "*** $CSCOMPILE" "$options -out:$name.$ext $i" > $testlogfile ; \
        if $CSCOMPILE $options -q -lib tests/ -out:$name.$ext $i >> $testlogfile 2>&1 ; then \
          if test -f $name.exe; then \
            echo "*** $TEST_RUNTIME -O=-all ./$name.exe" >> $testlogfile ; \
              if $TEST_RUNTIME -O=-all ./$name.exe >> $testlogfile 2>&1 ; then \
                  echo "PASS: $name"; \
                  rm -f $testlogfile;  \
              else \
                echo "Exit code: $?" >> $testlogfile ; \
                echo "FAIL: $name runtime"; \
              fi ; \
          else \
            echo "PASS: $name: compilation"; \
            rm -f $testlogfile ; \
          fi ; \
        else \
          echo "Exit code: $?" >> $testlogfile ; \
          echo "FAIL: $name: compilation"; \
        fi ; \
#        if test ! -f $testlogfile ; then :; else cat $testlogfile; fi
done;
