#!/bin/sh
DIR=`dirname $0`
echo "$DIR"
./$DIR/reil ncc exe ../misc/keys/Nemerle.Compiler.snk
./$DIR/reil Nemerle dll ../misc/keys/Nemerle.snk
./$DIR/reil Nemerle.Compiler dll ../misc/keys/Nemerle.Compiler.snk
./$DIR/reil Nemerle.Macros dll ../misc/keys/Nemerle.Compiler.snk
