#!/bin/sh
DIR=`dirname $0`
./$DIR/ildasm $1.$2 > temp.il
sed -e 's/ver 1:0:5000/ver 2:0:3600/' temp.il | sed -e 's/special-name/specialname/' > $1.il
./$DIR/ilasm /quiet /key=$3 /$2 $1.il
rm $1.il
rm temp.il
