name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
jobs:
  build:
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: true
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - name: Build
      run: |
        set MSBuild="%SystemRoot%\Microsoft.NET\Framework\v4.0.30319\msbuild.exe"
        %MSBuild% NemerleAll.nproj /t:InstallerFull /tv:4.0 /p:TargetFrameworkVersion=v4.0;Configuration=Release
      shell: cmd
    - name: Remove wixpdb
      run: Remove-Item bin\Release\net-4.0\Installer\*.wixpdb
    - uses: actions/upload-artifact@v2
      with:
        name: SetupAndBinaries
        path: bin/Release/net-4.0/Installer/

